### ISSUE TITLE
can we use DIT4C?

### ISSUE THREAD

**Issue by andreabedini** [CurtinIDS/SWC-2016-07-18#1]
ping @tjdett

**Comment by tjdett** [comment]
@andreabedini Assuming I can reuse the resources from ResBaz Perth, sure!

**Comment by andreabedini** [comment]
@tjdett tell me what you need :)

**Comment by tjdett** [comment]
1. Authorization from @arohl or @chrisbpawsey to use the resources at Pawsey Supercomputing Centre available through via the `SWC-Perth` NeCTAR RC tenant for this.
2. Another ping sometime in the first week of July so I can set this up for you.

**Comment by andreabedini** [comment]
@arohl is away for two weeks. I'll follow this up. Thanks @tjdett.

**Comment by andreabedini** [comment]
We decided we won't use DIT4C for software carpentry because we prefer people having their own laptop setup.

@tjdett I'm still interested in using DIT4C for research though.
